name: CI for Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Install dependencies
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    # Run linters
    - name: Run ESLint
      run: yarn lint

    # Run tests
    - name: Run Jest tests
      env:
        CI: true
      run: yarn test
